// Code generated by protoc-gen-go. DO NOT EDIT.
// source: go_sum.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SumRequest struct {
	Numbers              []int32  `protobuf:"varint,1,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumRequest) Reset()         { *m = SumRequest{} }
func (m *SumRequest) String() string { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()    {}
func (*SumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7087f4e76c317a04, []int{0}
}

func (m *SumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRequest.Unmarshal(m, b)
}
func (m *SumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRequest.Marshal(b, m, deterministic)
}
func (m *SumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRequest.Merge(m, src)
}
func (m *SumRequest) XXX_Size() int {
	return xxx_messageInfo_SumRequest.Size(m)
}
func (m *SumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumRequest proto.InternalMessageInfo

func (m *SumRequest) GetNumbers() []int32 {
	if m != nil {
		return m.Numbers
	}
	return nil
}

type SumResult struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumResult) Reset()         { *m = SumResult{} }
func (m *SumResult) String() string { return proto.CompactTextString(m) }
func (*SumResult) ProtoMessage()    {}
func (*SumResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_7087f4e76c317a04, []int{1}
}

func (m *SumResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumResult.Unmarshal(m, b)
}
func (m *SumResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumResult.Marshal(b, m, deterministic)
}
func (m *SumResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumResult.Merge(m, src)
}
func (m *SumResult) XXX_Size() int {
	return xxx_messageInfo_SumResult.Size(m)
}
func (m *SumResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SumResult.DiscardUnknown(m)
}

var xxx_messageInfo_SumResult proto.InternalMessageInfo

func (m *SumResult) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*SumRequest)(nil), "proto.SumRequest")
	proto.RegisterType((*SumResult)(nil), "proto.SumResult")
}

func init() { proto.RegisterFile("go_sum.proto", fileDescriptor_7087f4e76c317a04) }

var fileDescriptor_7087f4e76c317a04 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xcf, 0x8f, 0x2f,
	0x2e, 0xcd, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x6a, 0x5c, 0x5c,
	0xc1, 0xa5, 0xb9, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x12, 0x5c, 0xec, 0x79, 0xa5,
	0xb9, 0x49, 0xa9, 0x45, 0xc5, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xac, 0x41, 0x30, 0xae, 0x92, 0x32,
	0x17, 0x27, 0x58, 0x5d, 0x71, 0x69, 0x4e, 0x89, 0x90, 0x18, 0x17, 0x5b, 0x11, 0x98, 0x25, 0xc1,
	0xa8, 0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0xe5, 0x19, 0x59, 0x81, 0x0d, 0x0b, 0x4e, 0x2d, 0x2a, 0xcb,
	0x4c, 0x4e, 0x15, 0xd2, 0xe1, 0x62, 0x0e, 0x2e, 0xcd, 0x15, 0x12, 0x84, 0x58, 0xa8, 0x87, 0xb0,
	0x46, 0x4a, 0x00, 0x59, 0x08, 0xa4, 0x53, 0x89, 0xc1, 0xc9, 0x80, 0x4b, 0x3a, 0x33, 0x5f, 0x2f,
	0xbd, 0xa8, 0x20, 0x59, 0x2f, 0xb5, 0x22, 0x31, 0xb7, 0x20, 0x27, 0xb5, 0x58, 0xaf, 0x28, 0xbf,
	0xb4, 0x24, 0x35, 0xbd, 0x34, 0x33, 0x25, 0xd5, 0x89, 0x3f, 0x08, 0xc4, 0x76, 0x07, 0xb1, 0x03,
	0x40, 0x7a, 0x03, 0x18, 0x93, 0xd8, 0xc0, 0x86, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x04,
	0x1c, 0xe6, 0x06, 0xd8, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SumServiceClient is the client API for SumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SumServiceClient interface {
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResult, error)
}

type sumServiceClient struct {
	cc *grpc.ClientConn
}

func NewSumServiceClient(cc *grpc.ClientConn) SumServiceClient {
	return &sumServiceClient{cc}
}

func (c *sumServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResult, error) {
	out := new(SumResult)
	err := c.cc.Invoke(ctx, "/proto.SumService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SumServiceServer is the server API for SumService service.
type SumServiceServer interface {
	Sum(context.Context, *SumRequest) (*SumResult, error)
}

// UnimplementedSumServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSumServiceServer struct {
}

func (*UnimplementedSumServiceServer) Sum(ctx context.Context, req *SumRequest) (*SumResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}

func RegisterSumServiceServer(s *grpc.Server, srv SumServiceServer) {
	s.RegisterService(&_SumService_serviceDesc, srv)
}

func _SumService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SumServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SumService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SumServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SumService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SumService",
	HandlerType: (*SumServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _SumService_Sum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go_sum.proto",
}
